/** * @license * SPDX-License-Identifier: Apache-2.0 */import React, { useState, useCallback, useRef } from 'react';import { AnimatePresence, motion } from 'motion/react';import { CheckCircle, XCircle, Info, X } from 'lucide-react';import { cn } from '../../lib/utils';import { ToastContext, type Toast, type ToastType } from '../../hooks/useToast';/* --- Constants --- */
const AUTO_DISMISS_MS = 4000;

// --- Variant config ---
const VARIANT_CONFIG: Record< 
 ToastType,  { bg: string; icon: React.ReactNode; label: string }> = {  success: {    bg: 'bg-emerald-600',    icon: <CheckCircle className="w-5 h-5 shrink-0" aria-hidden="true" />,    label: 'Success',  },  error: {    bg: 'bg-brand-red',    icon: <XCircle className="w-5 h-5 shrink-0" aria-hidden="true" />,    label: 'Error',  },  info: {    bg: 'bg-indigo-600',    icon: <Info className="w-5 h-5 shrink-0" aria-hidden="true" />,    label: 'Info',  },};/* --- ToastProvider --- */
export function ToastProvider({ children }: { children: React.ReactNode }) { 
 const [toasts, setToasts] = useState<Toast[]>([]);  /* Keep a ref to timers so we can clear them on manual dismiss */ const timers = useRef<Map<string, ReturnType<typeof setTimeout>>>(new Map());  const dismissToast = useCallback((id: string) => {    setToasts((prev) => prev.filter((t) => t.id !== id));    const timer = timers.current.get(id);    if (timer !== undefined) {      clearTimeout(timer);      timers.current.delete(id);    }  }, []);  const showToast = useCallback(    (message: string, type: ToastType) => {      const id = `toast-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;      setToasts((prev) => [...prev, { id, message, type }]);      const timer = setTimeout(() => {        dismissToast(id);      }, AUTO_DISMISS_MS);      timers.current.set(id, timer);    },    [dismissToast]  );  return (    <ToastContext.Provider value={{ toasts, showToast, dismissToast }}>      {children}      <ToastContainer toasts={toasts} onDismiss={dismissToast} />    </ToastContext.Provider>  );}/* --- ToastContainer --- */
interface ToastContainerProps { 
 toasts: Toast[];  onDismiss: (id: string) => void;}function ToastContainer({ toasts, onDismiss }: ToastContainerProps) {  return (    <div      aria-live="polite"      aria-label="Notifications"      className="fixed top-4 right-4 z-[9999] flex flex-col gap-2 pointer-events-none"    >      <AnimatePresence initial={false}>        {toasts.map((toast) => (          <ToastItem key={toast.id} toast={toast} onDismiss={onDismiss} />        ))}      </AnimatePresence>    </div>  );}/* --- ToastItem --- */
interface ToastItemProps { 
 toast: Toast;  onDismiss: (id: string) => void;}function ToastItem({ toast, onDismiss }: ToastItemProps) {  const { bg, icon, label } = VARIANT_CONFIG[toast.type];  return (    <motion.div      role="alert"      aria-label={`${label}: ${toast.message}`}      initial={{ opacity: 0, x: 50 }}      animate={{ opacity: 1, x: 0 }}      exit={{ opacity: 0, x: 50 }}      transition={{ duration: 0.22, ease: 'easeOut' }}      className={cn(        'pointer-events-auto flex items-center gap-3 px-4 py-3',        'rounded-none shadow-lg text-white',        'min-w-[300px] max-w-[400px]',        bg      )}    >      {/* Icon */}      {icon}      {/* Message */}      <p className="flex-1 text-xs font-bold uppercase tracking-[0.15em] leading-snug">        {toast.message}      </p>      {/* Dismiss button */}      <button        onClick={() => onDismiss(toast.id)}        aria-label="Dismiss notification"        className="ml-1 p-1 opacity-70 hover:opacity-100 transition-opacity shrink-0"      >        <X className="w-3.5 h-3.5" />      </button>    </motion.div>  );}