import { AppNotification } from "./types";
export const mockNotifications: AppNotification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    title: "Resume Analysis Complete",
    message: "Your resume analysis is ready. ATS Score Improved by 12%.",
    type: "resume",
    priority: "high",
    isRead: false,
    createdAt: new Date().toISOString(),
    actionUrl: "/seeker/resume/analysis",
    actionLabel: "View Report",
  },
  {
    id: "notif-2",
    userId: "user-1",
    title: "New Job Match",
    message: "New Full Stack Engineer Match (92%) at TechCorp.",
    type: "job",
    priority: "medium",
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    /* 1 hour ago */ actionUrl: "/seeker/jobs/match-1",
    actionLabel: "View Job",
  },
  {
    id: "notif-3",
    userId: "user-1",
    title: "Interview Scheduled",
    message:
      "Your interview for Frontend Developer at StartupX is scheduled for tomorrow.",
    type: "application",
    priority: "high",
    isRead: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    /* 1 day ago */ actionUrl: "/seeker/applications/app-1",
    actionLabel: "View Application",
  },
  {
    id: "notif-4",
    userId: "user-1",
    title: "Application Moved to Review Stage",
    message:
      "Your application for Backend Engineer at Innovate Ltd is now in review.",
    type: "application",
    priority: "medium",
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    /* 2 days ago */ actionUrl: "/seeker/applications/app-2",
    actionLabel: "View Application",
  },
  {
    id: "notif-5",
    userId: "user-1",
    title: "Learning Milestone Reached",
    message:
      "Docker Skill Gap Closed! You have completed the Docker fundamentals course.",
    type: "learning",
    priority: "medium",
    isRead: false,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    /* 3 days ago */ actionUrl: "/seeker/learning",
    actionLabel: "Continue Learning",
  },
  {
    id: "notif-6",
    userId: "user-1",
    title: "Roadmap Milestone Completed",
    message:
      "You have completed the React hooks module in your Frontend Roadmap.",
    type: "learning",
    priority: "low",
    isRead: true,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    /* 4 days ago */ actionUrl: "/seeker/learning/roadmap",
    actionLabel: "View Roadmap",
  },
  {
    id: "notif-7",
    userId: "user-1",
    title: "Password Changed Successfully",
    message: "Your account password was updated recently.",
    type: "system",
    priority: "medium",
    isRead: true,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    /* 5 days ago */ actionUrl: "/seeker/profile",
    actionLabel: "View Profile",
  },
];
