import {
  SkillGap,
  LearningRoadmapCategory,
  CareerPath,
  RecommendedSkill,
  Resource,
} from "./types";
export const mockResources: Resource[] = [
  {
    id: "1",
    title: "System Design Interview ΓÇô An Insider's Guide",
    provider: "ByteByteGo",
    type: "Book",
    difficulty: "Advanced",
    duration: "Self-paced",
    url: "#",
    category: "SYSTEM DESIGN",
    recommendedReason: "Required for Full Stack Engineer Roadmap",
    description:
      "A comprehensive guide to cracking system design interviews with detailed case studies.",
    skillTags: ["System Design", "Architecture"],
    relatedCareerPaths: ["Full Stack Engineer", "Backend Engineer"],
    relatedSkills: ["System Architecture", "Scalability"],
  },
  {
    id: "2",
    title: "Docker & Kubernetes: The Practical Guide",
    provider: "Udemy",
    type: "Course",
    difficulty: "Intermediate",
    duration: "23 hours",
    url: "#",
    category: "DOCKER",
    recommendedReason: "Required to close Docker Skill Gap",
    description:
      "Learn Docker and Kubernetes from scratch with hands-on projects and deployments.",
    skillTags: ["Docker", "Kubernetes", "DevOps"],
    relatedCareerPaths: ["DevOps Engineer", "Backend Engineer"],
    relatedSkills: ["Containerization", "Orchestration"],
  },
  {
    id: "3",
    title: "AWS Certified Developer ΓÇô Associate",
    provider: "AWS Training",
    type: "Certification",
    difficulty: "Intermediate",
    duration: "40 hours",
    url: "#",
    category: "AWS",
    description:
      "Official certification preparation for AWS Certified Developer.",
    skillTags: ["AWS", "Cloud"],
    relatedCareerPaths: ["Cloud Engineer"],
    relatedSkills: ["Cloud Infrastructure", "Serverless"],
  },
  {
    id: "4",
    title: "Introduction to GraphQL",
    provider: "Apollo Docs",
    type: "Documentation",
    difficulty: "Beginner",
    duration: "3 hours",
    url: "#",
    category: "GRAPHQL",
    free: true,
    description: "Learn the basics of GraphQL queries, mutations, and schemas.",
    skillTags: ["GraphQL", "API"],
    relatedCareerPaths: ["Frontend Engineer", "Full Stack Engineer"],
    relatedSkills: ["API Integration"],
  },
  {
    id: "5",
    title: "TypeScript Deep Dive",
    provider: "Basarat Ali",
    type: "Book",
    difficulty: "Intermediate",
    duration: "Self-paced",
    url: "#",
    category: "TYPESCRIPT",
    free: true,
    description:
      "An open-source deep dive into TypeScript features and best practices.",
    skillTags: ["TypeScript", "JavaScript"],
    relatedCareerPaths: ["Frontend Engineer", "Full Stack Engineer"],
    relatedSkills: ["Static Typing"],
  },
  {
    id: "6",
    title: "Testing JavaScript with Kent C. Dodds",
    provider: "TestingJavaScript.com",
    type: "Course",
    difficulty: "Intermediate",
    duration: "8 hours",
    url: "#",
    category: "TESTING",
    description: "Master UI and unit testing for JavaScript applications.",
    skillTags: ["Testing", "Jest", "Cypress"],
    relatedCareerPaths: ["Frontend Engineer"],
    relatedSkills: ["TDD", "E2E Testing"],
  },
  {
    id: "7",
    title: "Redis University ΓÇô RU101",
    provider: "Redis",
    type: "Course",
    difficulty: "Beginner",
    duration: "6 hours",
    url: "#",
    category: "REDIS",
    free: true,
    description: "Introduction to Redis data structures and commands.",
    skillTags: ["Redis", "Caching"],
    relatedCareerPaths: ["Backend Engineer"],
    relatedSkills: ["In-memory Databases"],
  },
  {
    id: "8",
    title: "Node.js Best Practices",
    provider: "GitHub",
    type: "Documentation",
    difficulty: "Intermediate",
    duration: "Self-paced",
    url: "#",
    category: "NODE.JS",
    free: true,
    description:
      "Comprehensive collection of Node.js best practices and guidelines.",
    skillTags: ["Node.js", "Backend"],
    relatedCareerPaths: ["Backend Engineer"],
    relatedSkills: ["API Development"],
  },
];
export const mockSkillGaps: SkillGap[] = [
  {
    id: "g1",
    targetSkill: "System Design",
    currentLevel: 40,
    requiredLevel: 80,
    priority: "High",
    relatedResources: [mockResources[0]],
  },
  {
    id: "g2",
    targetSkill: "Docker",
    currentLevel: 30,
    requiredLevel: 80,
    priority: "High",
    relatedResources: [mockResources[1]],
  },
  {
    id: "g3",
    targetSkill: "AWS",
    currentLevel: 50,
    requiredLevel: 90,
    priority: "Medium",
    relatedResources: [mockResources[2]],
  },
  {
    id: "g4",
    targetSkill: "GraphQL",
    currentLevel: 10,
    requiredLevel: 70,
    priority: "Low",
    relatedResources: [mockResources[3]],
  },
];
export const mockRoadmaps: LearningRoadmapCategory[] = [
  {
    id: "r1",
    name: "Frontend Engineer",
    description: "Master UI, state, and web performance.",
    skills: ["React", "Next.js", "Tailwind", "TypeScript", "Web Vitals"],
    color: "#2563EB",
    difficulty: "Intermediate",
    progress: 35,
    estimatedTime: "3-6 months",
    learningSequence: [
      "Advanced JavaScript",
      "React Mastery",
      "State Management",
      "Web Performance",
    ],
    recommendedResources: [mockResources[4], mockResources[5]],
  },
  {
    id: "r2",
    name: "Backend Engineer",
    description: "Build scalable APIs and microservices.",
    skills: ["Node.js", "Python", "PostgreSQL", "Redis", "Docker"],
    color: "#8B5CF6",
    difficulty: "Advanced",
    progress: 10,
    estimatedTime: "6-9 months",
    learningSequence: [
      "API Design",
      "Database Modeling",
      "Caching Strategies",
      "Microservices Architecture",
    ],
    recommendedResources: [mockResources[6], mockResources[7]],
  },
  {
    id: "r3",
    name: "Full Stack Engineer",
    description: "End-to-end web application development.",
    skills: ["React", "Node.js", "System Design", "Databases"],
    color: "#10B981",
    difficulty: "Advanced",
    progress: 20,
    estimatedTime: "6-12 months",
    learningSequence: [
      "Frontend Frameworks",
      "Backend APIs",
      "System Design",
      "Deployment",
    ],
    recommendedResources: [mockResources[0]],
  },
  {
    id: "r4",
    name: "AI Engineer",
    description: "Build intelligent applications and ML models.",
    skills: ["Python", "PyTorch", "LLMs", "Vector DBs"],
    color: "#EC4899",
    difficulty: "Advanced",
    progress: 0,
    estimatedTime: "9-12 months",
    learningSequence: [
      "Python Deep Dive",
      "Machine Learning Basics",
      "Deep Learning",
      "LLMs & RAG",
    ],
  },
  {
    id: "r5",
    name: "Cloud Engineer",
    description: "Deploy and manage cloud infrastructure.",
    skills: ["AWS", "CI/CD", "Terraform", "Networking"],
    color: "#06B6D4",
    difficulty: "Intermediate",
    progress: 5,
    estimatedTime: "4-6 months",
    learningSequence: [
      "Cloud Fundamentals",
      "Networking & Security",
      "Infrastructure as Code",
      "CI/CD Pipelines",
    ],
    recommendedResources: [mockResources[2]],
  },
  {
    id: "r6",
    name: "DevOps Engineer",
    description: "Streamline development and operations.",
    skills: ["Kubernetes", "Docker", "Linux", "Jenkins"],
    color: "#F59E0B",
    difficulty: "Advanced",
    progress: 15,
    estimatedTime: "6-9 months",
    learningSequence: [
      "Linux Administration",
      "Containerization",
      "Orchestration",
      "Monitoring & Logging",
    ],
    recommendedResources: [mockResources[1]],
  },
];
export const mockCareers: CareerPath[] = [
  {
    id: "c1",
    title: "Full Stack Engineer",
    matchScore: 85,
    salaryRange: "$140k - $180k",
    requiredSkills: ["System Design", "React", "Node.js", "AWS"],
  },
  {
    id: "c2",
    title: "Cloud Engineer",
    matchScore: 72,
    salaryRange: "$130k - $170k",
    requiredSkills: ["AWS", "Terraform", "Docker", "Kubernetes"],
  },
  {
    id: "c3",
    title: "Solutions Architect",
    matchScore: 68,
    salaryRange: "$150k - $190k",
    requiredSkills: ["System Design", "AWS", "Microservices", "Communication"],
  },
];
export const mockRecommendedSkills: RecommendedSkill[] = [
  {
    id: "s1",
    name: "System Design",
    priority: "High",
    difficulty: "Advanced",
    relatedCareers: ["Senior Engineer", "Architect"],
  },
  {
    id: "s2",
    name: "GraphQL",
    priority: "Medium",
    difficulty: "Intermediate",
    relatedCareers: ["Full Stack Developer"],
  },
  {
    id: "s3",
    name: "Docker",
    priority: "Low",
    difficulty: "Beginner",
    relatedCareers: ["Backend Engineer", "DevOps"],
  },
];
